### PR TITLE
diskfree fails builds on node12, swap w diskusage

### PR DESCRIPTION
**Pull request by andreaslof**
`diskfree` is currently causing the package to fail on Node 12 (and seems to be somewhat stale in terms of maintenance), and `diskusage` should be safe to use (see: https://github.com/jduncanator/node-diskusage/issues/42#issuecomment-502565263)

### CODE REVIEW

**Comment by andreaslof** [comment]
Swapping `diskfree` with `diskusage` highlights that `node-usage` instead fails 😬 will try and patch that as well.

**Comment by chee** [comment]
@andreaslof thanks for this! the github page for `node-usage` mentions this module that has no binary component: https://github.com/soyuka/pidusage

**Comment by andreaslof** [comment]
@chee amazing, thank you! Will swap `node-usage` with that

**Comment by andreaslof** [comment]
This is `200 OK` for review now 🎉

**Pull request merged**
